# Generated by Django 4.0.4 on 2022-05-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_processes_for_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processes',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.RenameField(
            model_name='processes',
            old_name='for_delete',
            new_name='processData',
        ),
        migrations.RemoveField(
            model_name='processes',
            name='name',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
